<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RazasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('razas')->insert([

        //Perros
        ['raza'=> 'Criollo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Affenpinscher','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Airedale terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Akita','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Akita americano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Alaskan Husky','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Alaskan malamute','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'American Foxhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'American pit bull terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'American staffordshire terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Ariegeois','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Artois','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Australian silky terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Australian Terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Austrian Black & Tan Hound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Azawakh','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Balkan Hound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basenji','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset Alpino (Alpine Dachsbracke)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset Artesiano Normando','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset Azul de Gascuña (Basset Bleu de Gascogne)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset de Artois','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset de Westphalie','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset Hound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Basset Leonado de Bretaña (Basset fauve de Bretagne)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bavarian Mountain Scenthound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Beagle','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Beagle Harrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Beauceron','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bedlington Terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bichon Boloñes','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bichón Frisé','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bichón Habanero','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Billy','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Black and Tan Coonhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bloodhound (Sabueso de San Huberto)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bobtail','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boerboel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Border Collie','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Border terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Borzoi','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bosnian Hound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boston terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bouvier des Flandres','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boxer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boyero de Appenzell','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boyero de Australia','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boyero de Entlebuch','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boyero de las Ardenas','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Boyero de Montaña Bernes','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco Alemán de pelo corto','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco Alemán de pelo duro','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco de Ariege','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco de Auvernia','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco de Bourbonnais','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco de Saint Germain','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco Dupuy','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco Francés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Braco Italiano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Broholmer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Buhund Noruego','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bull terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bulldog americano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bulldog inglés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bulldog francés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Bullmastiff','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Ca de Bestiar','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cairn terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cane Corso','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cane da Pastore Maremmano-Abruzzese','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Caniche (Poodle)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Caniche Toy (Toy Poodle)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cao da Serra de Aires','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cao da Serra de Estrela','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cao de Castro Laboreiro','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cao de Fila de Sao Miguel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cavalier King Charles Spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cesky Fousek','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cesky Terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Chesapeake Bay Retriever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Chihuahua','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Chin','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Chow Chow','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cirneco del Etna','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Clumber Spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cocker Spaniel Americano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cocker Spaniel Inglés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Collie Barbudo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Collie de Pelo Cort','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Collie de Pelo Largo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Cotón de Tuléar','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Curly Coated Retriever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dálmata','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dandie dinmont terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Deerhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dobermann','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dogo Argentino','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dogo de Burdeos','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dogo del Tibet','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Drentse Partridge Dog','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Drever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Dunker','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Elkhound Noruego','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Elkhound Sueco','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'English Foxhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'English Springer Spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'English Toy Terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Epagneul Picard','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Eurasier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Fila Brasileiro','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Finnish Lapphound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Flat Coated Retriever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Fox terrier de pelo de alambre','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Fox terrier de pelo liso','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Foxhound Inglés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Frisian Pointer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Galgo Español','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Galgo húngaro (Magyar Agar)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Galgo Italiano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Galgo Polaco (Chart Polski)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Glen of Imaal Terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Golden Retriever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gordon Setter','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gos d´Atura Catalá','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Basset Griffon Vendeano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Boyero Suizo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Danés (Dogo Aleman)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Gascón Saintongeois','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Griffon Vendeano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Munsterlander','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Gran Perro Japonés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Grand Anglo Francais Tricoleur','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Grand Bleu de Gascogne','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Greyhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Griffon Bleu de Gascogne','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Griffon de pelo duro (Grifón Korthals)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Griffon leonado de Bretaña','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Griffon Nivernais','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Grifon Belga','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Grifón de Bruselas','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Haldenstoever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Harrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Hokkaido','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Hovawart','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Husky Siberiano (Siberian Husky)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Ioujnorousskaia Ovtcharka','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Irish Glen of Imaal terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Irish soft coated wheaten terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Irish terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Irish Water Spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Irish Wolfhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Jack Russell terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Jindo Coreano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kai','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Keeshond','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kelpie australiano (Australian kelpie)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kerry blue terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'King Charles Spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kishu','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Komondor','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kooiker','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kromfohrländer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Kuvasz','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Labrador Retriever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lagotto Romagnolo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Laika de Siberia Occidental','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Laika de Siberia Oriental','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Laika Ruso Europeo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lakeland terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Landseer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lapphund Sueco','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lebrel Afgano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lebrel Arabe (Sloughi)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Leonberger','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lhasa Apso','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lowchen (Pequeño Perro León)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Lundehund Noruego','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Malamute de Alaska','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Maltés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Manchester terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Mastiff','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Mastín de los Pirineos','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Mastín Español','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Mastín Napolitano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Mudi','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Norfolk terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Norwich terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Nova Scotia duck tolling retriever','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Ovejero alemán','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Otterhound','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Rafeiro do Alentejo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Ratonero Bodeguero Andaluz','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Retriever de Nueva Escocia','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Rhodesian Ridgeback','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Ridgeback de Tailandia','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Rottweiler','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Saarloos','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Hamilton','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Hannover','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Hygen','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Istria','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Posavaz','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Schiller (Schillerstovare)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Smaland (Smalandsstovare)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso de Transilvania','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso del Tirol','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Español','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Estirio de pelo duro','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Finlandés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Francés blanco y negro','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Francés tricolor','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Griego','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Polaco (Ogar Polski)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Serbio','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Suizo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Yugoslavo de Montaña','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sabueso Yugoslavo tricolor','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Saluki','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Samoyedo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'San Bernardo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sarplaninac','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Schapendoes','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Schipperke','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Schnauzer estándar','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Schnauzer gigante (Riesenschnauzer)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Schnauzer miniatura (Zwergschnauzer)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Scottish terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sealyham terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Segugio Italiano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Seppala Siberiano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Setter Inglés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Setter Irlandés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Setter Irlandés rojo y blanco','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Shar Pei','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Shiba Inu','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Shih Tzu','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Shikoku','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Skye terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Slovensky Cuvac','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Slovensky Kopov','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Smoushond Holandés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel Alemán (German Wachtelhund)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel Azul de Picardía','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel Bretón','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel de Campo','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel de Pont Audemer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel Francés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spaniel Tibetano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spinone Italiano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spítz Alemán','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spitz de Norbotten (Norbottenspets)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spitz Finlandés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Spitz Japonés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Staffordshire bull terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Staffordshire terrier americano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Sussex Spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Teckel (Dachshund)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Tchuvatch eslovaco','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terranova (Newfoundland)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier australiano (Australian terrier)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier brasilero','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier cazador alemán','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier checo (Ceský teriér)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier galés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier irlandés (Irish terrier)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier japonés (Nihon teria)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier negro ruso','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Terrier tibetano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Tosa','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Viejo Pastor Inglés','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Viejo Pointer Danés (Old Danish Pointer)','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Vizsla','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Volpino Italiano','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Weimaraner','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Welsh springer spaniel','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Welsh Corgi Cardigan','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Welsh Corgi Pembroke','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Welsh terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'West highland white terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Whippet','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Wirehaired solvakian pointer','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Xoloitzcuintle','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],
        ['raza'=> 'Yorkshire Terrier','especies_id'=> 1, 'create_at'=> now(), 'update_at'=> now ()],


        ]);

         DB::table('razas')->insert([

        //Gatos

        ['raza' => 'Criollo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Abisinio','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'American Curl','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Azul ruso','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'American shorthair','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'American wirehair','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Angora turco','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Africano doméstico','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Bengala','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Bobtail japonés','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Bombay','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Bosque de Noruega','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Brazilian Shorthair','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Brivon de pelo corto','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Brivon de pelo largo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'British Shorthair','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'British Longhair','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Burmés','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Burmilla','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Cornish rex','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'California Spangled','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Cymric','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Chartreux','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Gato Carey','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Devon rex','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Dorado africano','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Don Sphynx','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Dragon Li','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Gato común europeo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Exótico de pelo corto','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Gato europeo bicolor','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'gato elfo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'FoldEx','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'German Rex','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Habana brown','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Himalayo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Korat','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Khao Manee','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Manx','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Mau egipcio','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Munchkin','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Ocicat','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Oriental','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Oriental de pelo largo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Persa americano o moderno','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Peterbald','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Pixie Bob','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Gato rojo','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Ragdoll','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Sagrado de Birmania','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Savannah','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Scottish Fold','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Selkirk rex','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Serengeti','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Seychellois','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Siamés','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Siamés Moderno','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Siamés Tradicional','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Siberiano','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Snowshoe','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Sphynx','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Tonkinés','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Toyger','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],
        ['raza' => 'Van Turco','especies_id' => 2, 'create_at' => now(), 'update_at' => now ()],

         ]);


    }
}
